import { initializeApp } from 'firebase/app'
import { getFirestore, collection, addDoc } from 'firebase/firestore'
import { getAuth, signInAnonymously } from 'firebase/auth'
import { readFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, resolve } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const env = readFileSync(resolve(__dirname, '../../.env.local'), 'utf-8')
const vars = Object.fromEntries(env.split('\n').filter(l => l.includes('=')).map(l => l.split('=')))

const app = initializeApp({
  apiKey:            vars.VITE_FIREBASE_API_KEY?.trim(),
  authDomain:        vars.VITE_FIREBASE_AUTH_DOMAIN?.trim(),
  projectId:         vars.VITE_FIREBASE_PROJECT_ID?.trim(),
  storageBucket:     vars.VITE_FIREBASE_STORAGE_BUCKET?.trim(),
  messagingSenderId: vars.VITE_FIREBASE_MESSAGING_SENDER_ID?.trim(),
  appId:             vars.VITE_FIREBASE_APP_ID?.trim(),
})
const db = getFirestore(app)
const auth = getAuth(app)

const questions = [
  // ─── ENGLISH — Beginner (50) ───────────────────────────────────────────────
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What colour is grass?', options:['Green','Red','Blue','Yellow'], answer:'Green' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'Which animal can fly?', options:['Bird','Cat','Dog','Fish'], answer:'Bird' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What do you use to eat soup?', options:['Spoon','Fork','Knife','Cup'], answer:'Spoon' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'Which is a fruit?', options:['Apple','Carrot','Potato','Bread'], answer:'Apple' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What day comes after Tuesday?', options:['Wednesday','Monday','Thursday','Friday'], answer:'Wednesday' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'How many wheels does a bicycle have?', options:['2','3','4','1'], answer:'2' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What colour is the sky on a sunny day?', options:['Blue','Green','Purple','Orange'], answer:'Blue' },
  { subject:'english', type:'fillBlank',     difficulty:'beginner', question:'She ___ a red dress.', options:['wears','wear','wearing','wore'], answer:'wears' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'Which animal lives in the sea?', options:['Fish','Cat','Dog','Rabbit'], answer:'Fish' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What do we use to write?', options:['Pen','Spoon','Fork','Cup'], answer:'Pen' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What is the opposite of "hot"?', options:['Cold','Warm','Dark','Fast'], answer:'Cold' },
  { subject:'english', type:'fillBlank',     difficulty:'beginner', question:'___ are you? (greeting)', options:['How','Who','What','Where'], answer:'How' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'Which animal has a long trunk?', options:['Elephant','Lion','Tiger','Bear'], answer:'Elephant' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What do we wear on our feet?', options:['Shoes','Hat','Gloves','Scarf'], answer:'Shoes' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What colour is a banana?', options:['Yellow','Orange','Red','Purple'], answer:'Yellow' },
  { subject:'english', type:'fillBlank',     difficulty:'beginner', question:'I have ___ eyes.', options:['two','three','four','one'], answer:'two' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'Which meal do we eat in the morning?', options:['Breakfast','Lunch','Dinner','Supper'], answer:'Breakfast' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What sound does a duck make?', options:['Quack','Moo','Woof','Meow'], answer:'Quack' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'How many days are in a week?', options:['7','5','6','8'], answer:'7' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What is a baby cat called?', options:['Kitten','Puppy','Cub','Lamb'], answer:'Kitten' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What do we use to cut paper?', options:['Scissors','Pen','Ruler','Eraser'], answer:'Scissors' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What is the opposite of "up"?', options:['Down','Left','Right','Front'], answer:'Down' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'Which animal gives us milk?', options:['Cow','Dog','Cat','Horse'], answer:'Cow' },
  { subject:'english', type:'fillBlank',     difficulty:'beginner', question:'We sleep at ___.', options:['night','day','morning','noon'], answer:'night' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'How many months are in a year?', options:['12','10','11','13'], answer:'12' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What do bees make?', options:['Honey','Milk','Butter','Juice'], answer:'Honey' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'Which is a vegetable?', options:['Broccoli','Apple','Mango','Banana'], answer:'Broccoli' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What colour is a frog?', options:['Green','Red','Blue','Yellow'], answer:'Green' },
  { subject:'english', type:'fillBlank',     difficulty:'beginner', question:'She ___ a book in her bag.', options:['has','have','had','is'], answer:'has' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What sound does a cow make?', options:['Moo','Woof','Meow','Cluck'], answer:'Moo' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What colour is snow?', options:['White','Grey','Black','Blue'], answer:'White' },
  { subject:'english', type:'fillBlank',     difficulty:'beginner', question:'My favourite colour ___ blue.', options:['is','are','am','be'], answer:'is' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What number comes after 9?', options:['10','8','11','7'], answer:'10' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What is the opposite of "happy"?', options:['Sad','Angry','Tired','Hungry'], answer:'Sad' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'Which animal lays eggs?', options:['Chicken','Cow','Horse','Dog'], answer:'Chicken' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What do fish live in?', options:['Water','Land','Air','Sand'], answer:'Water' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'Which animal hops?', options:['Rabbit','Fish','Elephant','Cow'], answer:'Rabbit' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What do we say when we leave?', options:['Goodbye','Hello','Thanks','Sorry'], answer:'Goodbye' },
  { subject:'english', type:'fillBlank',     difficulty:'beginner', question:'We ___ with our ears.', options:['hear','see','smell','touch'], answer:'hear' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'How many sides does a square have?', options:['4','3','5','6'], answer:'4' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What colour is an orange?', options:['Orange','Yellow','Red','Green'], answer:'Orange' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What do we put on bread?', options:['Butter','Sand','Water','Leaves'], answer:'Butter' },
  { subject:'english', type:'fillBlank',     difficulty:'beginner', question:'The dog ___ in the park.', options:['runs','run','running','ran'], answer:'runs' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'How many fingers are on one hand?', options:['5','4','6','3'], answer:'5' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What is the opposite of "big"?', options:['Small','Tall','Fast','Dark'], answer:'Small' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'Which animal gives us eggs?', options:['Chicken','Cow','Horse','Dog'], answer:'Chicken' },
  { subject:'english', type:'fillBlank',     difficulty:'beginner', question:'The bird ___ in the tree.', options:['sits','sit','sitting','sate'], answer:'sits' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What shape is a wheel?', options:['Circle','Square','Triangle','Rectangle'], answer:'Circle' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'Which number is the smallest?', options:['1','3','5','8'], answer:'1' },
  { subject:'english', type:'vocabulary',    difficulty:'beginner', question:'What do we say to be polite when asking?', options:['Please','Hello','Goodbye','Sorry'], answer:'Please' },

  // ─── ENGLISH — Advanced (50) ──────────────────────────────────────────────
  { subject:'english', type:'vocabulary',    difficulty:'advanced', question:'What does "enormous" mean?', options:['Very large','Very fast','Very small','Very quiet'], answer:'Very large' },
  { subject:'english', type:'grammar',       difficulty:'advanced', question:'Choose the correct sentence:', options:['The children are playing.','The children is playing.','The children was playing.','The children am playing.'], answer:'The children are playing.' },
  { subject:'english', type:'synonyms',      difficulty:'advanced', question:'A synonym for "brave" is?', options:['Courageous','Fearful','Weak','Timid'], answer:'Courageous' },
  { subject:'english', type:'vocabulary',    difficulty:'advanced', question:'What does "peculiar" mean?', options:['Strange','Beautiful','Fast','Common'], answer:'Strange' },
  { subject:'english', type:'fillBlank',     difficulty:'advanced', question:'She has been studying ___ three hours.', options:['for','since','during','from'], answer:'for' },
  { subject:'english', type:'grammar',       difficulty:'advanced', question:'Which is grammatically correct?', options:["He doesn't like pizza.","He don't like pizza.","He doesn't likes pizza.","He not like pizza."], answer:"He doesn't like pizza." },
  { subject:'english', type:'vocabulary',    difficulty:'advanced', question:'Antonym of "ancient"?', options:['Modern','Old','Historic','Classic'], answer:'Modern' },
  { subject:'english', type:'comprehension', difficulty:'advanced', question:'"The exhausted hiker finally reached the summit." What does "summit" mean?', options:['Mountain top','Valley','River','Forest'], answer:'Mountain top' },
  { subject:'english', type:'synonyms',      difficulty:'advanced', question:'Synonym for "difficult"?', options:['Challenging','Easy','Simple','Quick'], answer:'Challenging' },
  { subject:'english', type:'grammar',       difficulty:'advanced', question:'Complete: "If I ___ you, I would study harder."', options:['were','was','am','be'], answer:'were' },
  { subject:'english', type:'vocabulary',    difficulty:'advanced', question:'"Transparent" means?', options:['See-through','Colourful','Opaque','Shiny'], answer:'See-through' },
  { subject:'english', type:'fillBlank',     difficulty:'advanced', question:'The train ___ at 9am every day.', options:['departs','departed','has departed','departing'], answer:'departs' },
  { subject:'english', type:'vocabulary',    difficulty:'advanced', question:'What does "nocturnal" mean?', options:['Active at night','Fast runner','Very noisy','Living in water'], answer:'Active at night' },
  { subject:'english', type:'grammar',       difficulty:'advanced', question:'Which uses the correct past tense?', options:['Yesterday I went to school.','Yesterday I go to school.','Yesterday I goes to school.','Yesterday I gone to school.'], answer:'Yesterday I went to school.' },
  { subject:'english', type:'synonyms',      difficulty:'advanced', question:'Synonym for "wealthy"?', options:['Rich','Poor','Hungry','Tired'], answer:'Rich' },
  { subject:'english', type:'vocabulary',    difficulty:'advanced', question:'"Microscopic" means?', options:['Extremely tiny','Very large','Very bright','Very loud'], answer:'Extremely tiny' },
  { subject:'english', type:'comprehension', difficulty:'advanced', question:'"Despite the rain, the match continued." What does "despite" mean?', options:['Even though','Because','After','Before'], answer:'Even though' },
  { subject:'english', type:'grammar',       difficulty:'advanced', question:'"She ___ her homework before dinner."', options:['had finished','has finish','finishes','finishing'], answer:'had finished' },
  { subject:'english', type:'vocabulary',    difficulty:'advanced', question:'Antonym of "generous"?', options:['Selfish','Kind','Giving','Caring'], answer:'Selfish' },
  { subject:'english', type:'fillBlank',     difficulty:'advanced', question:'The students ___ excited about the field trip.', options:['were','was','is','am'], answer:'were' },
  { subject:'english', type:'vocabulary',    difficulty:'advanced', question:'"Cunning" means?', options:['Clever and sly','Very kind','Extremely brave','Highly loyal'], answer:'Clever and sly' },
  { subject:'english', type:'grammar',       difficulty:'advanced', question:'Choose the correct plural:', options:['The children played.','The childs played.','The childrens played.','The childes played.'], answer:'The children played.' },
  { subject:'english', type:'comprehension', difficulty:'advanced', question:'"The detective scrutinised the evidence." What does "scrutinised" mean?', options:['Examined carefully','Threw away','Ignored','Collected'], answer:'Examined carefully' },
  { subject:'english', type:'synonyms',      difficulty:'advanced', question:'Synonym for "exhausted"?', options:['Tired','Energetic','Happy','Confused'], answer:'Tired' },
  { subject:'english', type:'vocabulary',    difficulty:'advanced', question:'"Ambiguous" means?', options:['Having more than one meaning','Very clear','Completely wrong','Very simple'], answer:'Having more than one meaning' },
  { subject:'english', type:'grammar',       difficulty:'advanced', question:'"Neither the cat nor the dog ___ eating."', options:['is','are','were','been'], answer:'is' },
  { subject:'english', type:'fillBlank',     difficulty:'advanced', question:'It was ___ cold that we stayed indoors.', options:['so','such','very','too'], answer:'so' },
  { subject:'english', type:'vocabulary',    difficulty:'advanced', question:'"Serene" means?', options:['Calm and peaceful','Noisy and busy','Dark and stormy','Hot and dry'], answer:'Calm and peaceful' },
  { subject:'english', type:'grammar',       difficulty:'advanced', question:'Which sentence is passive voice?', options:['The man was bitten by the dog.','The dog bit the man.','The man bites the dog.','The dog is biting the man.'], answer:'The man was bitten by the dog.' },
  { subject:'english', type:'comprehension', difficulty:'advanced', question:'"The parched traveller drank eagerly." What does "parched" mean?', options:['Very thirsty','Very hungry','Very tired','Very cold'], answer:'Very thirsty' },
  { subject:'english', type:'vocabulary',    difficulty:'advanced', question:'Antonym of "cowardly"?', options:['Brave','Scared','Timid','Shy'], answer:'Brave' },
  { subject:'english', type:'fillBlank',     difficulty:'advanced', question:'"He arrived ___ than expected."', options:['earlier','more early','earliest','most early'], answer:'earlier' },
  { subject:'english', type:'grammar',       difficulty:'advanced', question:'"The book ___ on the shelf for years."', options:['has been','have been','is been','was been'], answer:'has been' },
  { subject:'english', type:'synonyms',      difficulty:'advanced', question:'Synonym for "enormous"?', options:['Gigantic','Tiny','Average','Medium'], answer:'Gigantic' },
  { subject:'english', type:'vocabulary',    difficulty:'advanced', question:'"Diligent" means?', options:['Hardworking','Lazy','Noisy','Careless'], answer:'Hardworking' },
  { subject:'english', type:'comprehension', difficulty:'advanced', question:'"The mischievous puppy chewed the shoes." What does "mischievous" mean?', options:['Playfully naughty','Very kind','Very sleepy','Extremely hungry'], answer:'Playfully naughty' },
  { subject:'english', type:'grammar',       difficulty:'advanced', question:'Choose the correct comparative:', options:['She is taller than him.','She is more taller than him.','She is tallest than him.','She is tall than him.'], answer:'She is taller than him.' },
  { subject:'english', type:'vocabulary',    difficulty:'advanced', question:'"Vibrant" means?', options:['Bright and colourful','Dark and dull','Old and worn','Small and fragile'], answer:'Bright and colourful' },
  { subject:'english', type:'synonyms',      difficulty:'advanced', question:'Synonym for "commence"?', options:['Begin','End','Pause','Continue'], answer:'Begin' },
  { subject:'english', type:'vocabulary',    difficulty:'advanced', question:'"Resilient" means?', options:['Able to recover quickly','Easily broken','Always hungry','Very quiet'], answer:'Able to recover quickly' },
  { subject:'english', type:'grammar',       difficulty:'advanced', question:'"Each of the students ___ submitted their project."', options:['has','have','had','having'], answer:'has' },
  { subject:'english', type:'comprehension', difficulty:'advanced', question:'"The frugal shopper always looked for bargains." What does "frugal" mean?', options:['Careful with money','Very generous','Always happy','Very busy'], answer:'Careful with money' },
  { subject:'english', type:'vocabulary',    difficulty:'advanced', question:'Antonym of "transparent"?', options:['Opaque','Clear','Visible','Bright'], answer:'Opaque' },
  { subject:'english', type:'fillBlank',     difficulty:'advanced', question:'The movie was so boring that I fell ___.', options:['asleep','awake','apart','away'], answer:'asleep' },
  { subject:'english', type:'grammar',       difficulty:'advanced', question:'"___ did you speak to?" (formal)', options:['Whom','Who','Whose','Which'], answer:'Whom' },
  { subject:'english', type:'synonyms',      difficulty:'advanced', question:'Synonym for "ancient"?', options:['Old','New','Modern','Recent'], answer:'Old' },
  { subject:'english', type:'vocabulary',    difficulty:'advanced', question:'"Substantial" means?', options:['Large and significant','Very small','Completely empty','Extremely fast'], answer:'Large and significant' },
  { subject:'english', type:'comprehension', difficulty:'advanced', question:'"She persevered despite numerous setbacks." What does "persevered" mean?', options:['Kept trying','Gave up','Felt sad','Got angry'], answer:'Kept trying' },
  { subject:'english', type:'grammar',       difficulty:'advanced', question:'"The news ___ surprising."', options:['was','were','are','am'], answer:'was' },
  { subject:'english', type:'vocabulary',    difficulty:'advanced', question:'What does "benevolent" mean?', options:['Kind and generous','Cruel and mean','Loud and rude','Cold and distant'], answer:'Kind and generous' },
  { subject:'english', type:'synonyms',      difficulty:'advanced', question:'Synonym for "melancholy"?', options:['Sad','Happy','Angry','Excited'], answer:'Sad' },

  // ─── MATHS — Beginner (50) ────────────────────────────────────────────────
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'1 + 1 = ?', options:['2','3','4','1'], answer:'2' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'5 + 3 = ?', options:['7','8','9','6'], answer:'8' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'10 − 4 = ?', options:['5','6','7','8'], answer:'6' },
  { subject:'maths', type:'shapes',     difficulty:'beginner', question:'How many sides does a circle have?', options:['0','1','2','4'], answer:'0' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'2 + 2 = ?', options:['3','4','5','6'], answer:'4' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'7 − 3 = ?', options:['3','4','5','6'], answer:'4' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'What number comes before 10?', options:['9','8','11','12'], answer:'9' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'6 + 4 = ?', options:['8','9','10','11'], answer:'10' },
  { subject:'maths', type:'shapes',     difficulty:'beginner', question:'A rectangle has how many corners?', options:['4','3','5','6'], answer:'4' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'8 − 5 = ?', options:['2','3','4','5'], answer:'3' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'What number comes after 15?', options:['16','14','17','18'], answer:'16' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'4 + 5 = ?', options:['7','8','9','10'], answer:'9' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'10 − 7 = ?', options:['2','3','4','5'], answer:'3' },
  { subject:'maths', type:'shapes',     difficulty:'beginner', question:'How many sides does a pentagon have?', options:['4','5','6','7'], answer:'5' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'3 + 6 = ?', options:['7','8','9','10'], answer:'9' },
  { subject:'maths', type:'money',      difficulty:'beginner', question:'You have 5 coins and spend 2. How many are left?', options:['2','3','4','5'], answer:'3' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'1 + 4 + 2 = ?', options:['6','7','8','9'], answer:'7' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'Which number is biggest? 3, 7, 5, 2', options:['7','5','3','2'], answer:'7' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'9 − 6 = ?', options:['2','3','4','5'], answer:'3' },
  { subject:'maths', type:'shapes',     difficulty:'beginner', question:'How many sides does a hexagon have?', options:['4','5','6','7'], answer:'6' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'5 + 5 = ?', options:['8','9','10','11'], answer:'10' },
  { subject:'maths', type:'time',       difficulty:'beginner', question:'How many hours are in a day?', options:['24','12','7','30'], answer:'24' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'6 + 3 = ?', options:['8','9','10','7'], answer:'9' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'7 − 4 = ?', options:['2','3','4','5'], answer:'3' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'2 + 2 + 2 = ?', options:['4','5','6','7'], answer:'6' },
  { subject:'maths', type:'shapes',     difficulty:'beginner', question:'A triangle has how many corners?', options:['2','3','4','5'], answer:'3' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'8 + 2 = ?', options:['9','10','11','12'], answer:'10' },
  { subject:'maths', type:'time',       difficulty:'beginner', question:'How many minutes are in an hour?', options:['60','30','90','120'], answer:'60' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'4 − 1 = ?', options:['2','3','4','5'], answer:'3' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'3 + 3 = ?', options:['5','6','7','8'], answer:'6' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'Which number is smallest? 9, 6, 2, 8', options:['2','6','8','9'], answer:'2' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'5 + 2 = ?', options:['6','7','8','9'], answer:'7' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'10 − 3 = ?', options:['6','7','8','9'], answer:'7' },
  { subject:'maths', type:'shapes',     difficulty:'beginner', question:'Which shape has no flat sides?', options:['Circle','Square','Rectangle','Triangle'], answer:'Circle' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'1 + 3 = ?', options:['3','4','5','6'], answer:'4' },
  { subject:'maths', type:'money',      difficulty:'beginner', question:'You have 10 coins and get 5 more. How many now?', options:['13','14','15','16'], answer:'15' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'6 − 2 = ?', options:['3','4','5','6'], answer:'4' },
  { subject:'maths', type:'time',       difficulty:'beginner', question:'How many days are in a week?', options:['7','5','6','8'], answer:'7' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'7 + 2 = ?', options:['8','9','10','11'], answer:'9' },
  { subject:'maths', type:'sequences',  difficulty:'beginner', question:'Count by 10s: 10, 20, 30, ___?', options:['35','40','45','50'], answer:'40' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'9 − 9 = ?', options:['0','1','2','3'], answer:'0' },
  { subject:'maths', type:'shapes',     difficulty:'beginner', question:'A square has how many equal sides?', options:['2','3','4','5'], answer:'4' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'2 + 8 = ?', options:['8','9','10','11'], answer:'10' },
  { subject:'maths', type:'time',       difficulty:'beginner', question:'How many months are in a year?', options:['12','10','11','13'], answer:'12' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'5 − 0 = ?', options:['4','5','6','7'], answer:'5' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'Which is an even number?', options:['8','3','5','7'], answer:'8' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'4 + 4 = ?', options:['6','7','8','9'], answer:'8' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'10 − 1 = ?', options:['8','9','10','11'], answer:'9' },
  { subject:'maths', type:'shapes',     difficulty:'beginner', question:'Which shape has 8 sides?', options:['Octagon','Hexagon','Heptagon','Pentagon'], answer:'Octagon' },
  { subject:'maths', type:'arithmetic', difficulty:'beginner', question:'3 + 7 = ?', options:['9','10','11','12'], answer:'10' },

  // ─── MATHS — Advanced (50) ────────────────────────────────────────────────
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'6 × 7 = ?', options:['36','42','48','54'], answer:'42' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'81 ÷ 9 = ?', options:['7','8','9','10'], answer:'9' },
  { subject:'maths', type:'wordProblems',  difficulty:'advanced', question:'A box has 5 rows of 6 apples. How many apples in total?', options:['25','30','35','40'], answer:'30' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'15 × 4 = ?', options:['50','55','60','65'], answer:'60' },
  { subject:'maths', type:'sequences',     difficulty:'advanced', question:'5, 10, 15, 20, ___?', options:['22','24','25','30'], answer:'25' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'200 − 75 = ?', options:['115','120','125','130'], answer:'125' },
  { subject:'maths', type:'wordProblems',  difficulty:'advanced', question:'Sam has 48 candies shared equally among 6 friends. How many does each get?', options:['6','7','8','9'], answer:'8' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'9 × 9 = ?', options:['72','81','90','99'], answer:'81' },
  { subject:'maths', type:'sequences',     difficulty:'advanced', question:'3, 6, 12, 24, ___?', options:['36','42','48','56'], answer:'48' },
  { subject:'maths', type:'wordProblems',  difficulty:'advanced', question:'A pencil costs $3. How much do 7 pencils cost?', options:['$18','$21','$24','$27'], answer:'$21' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'132 ÷ 11 = ?', options:['10','11','12','13'], answer:'12' },
  { subject:'maths', type:'shapes',        difficulty:'advanced', question:'Area of a rectangle 5cm × 4cm?', options:['16cm²','18cm²','20cm²','22cm²'], answer:'20cm²' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'8 × 8 = ?', options:['56','60','64','72'], answer:'64' },
  { subject:'maths', type:'sequences',     difficulty:'advanced', question:'100, 90, 80, 70, ___?', options:['55','60','65','68'], answer:'60' },
  { subject:'maths', type:'wordProblems',  difficulty:'advanced', question:'3 bags each have 12 marbles. How many marbles in total?', options:['30','33','36','39'], answer:'36' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'125 + 75 = ?', options:['190','195','200','205'], answer:'200' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'56 ÷ 8 = ?', options:['6','7','8','9'], answer:'7' },
  { subject:'maths', type:'shapes',        difficulty:'advanced', question:'Perimeter of a square with side 6cm?', options:['18cm','20cm','22cm','24cm'], answer:'24cm' },
  { subject:'maths', type:'wordProblems',  difficulty:'advanced', question:'A train travels 60km per hour. How far in 3 hours?', options:['120km','150km','180km','200km'], answer:'180km' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'9 × 4 = ?', options:['32','34','36','38'], answer:'36' },
  { subject:'maths', type:'sequences',     difficulty:'advanced', question:'1, 4, 9, 16, ___? (square numbers)', options:['20','22','25','28'], answer:'25' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'250 − 130 = ?', options:['110','120','130','140'], answer:'120' },
  { subject:'maths', type:'wordProblems',  difficulty:'advanced', question:'Books cost $8 each. Tom has $40. How many can he buy?', options:['4','5','6','7'], answer:'5' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'12 × 5 = ?', options:['55','60','65','70'], answer:'60' },
  { subject:'maths', type:'logic',         difficulty:'advanced', question:'If all roses are flowers, and all flowers need water, do roses need water?', options:['Yes','No','Maybe','Sometimes'], answer:'Yes' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'72 ÷ 6 = ?', options:['10','11','12','13'], answer:'12' },
  { subject:'maths', type:'wordProblems',  difficulty:'advanced', question:'Jane has $50 and spends $17. How much is left?', options:['$31','$33','$35','$37'], answer:'$33' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'11 × 11 = ?', options:['111','112','120','121'], answer:'121' },
  { subject:'maths', type:'sequences',     difficulty:'advanced', question:'2, 5, 8, 11, ___?', options:['13','14','15','16'], answer:'14' },
  { subject:'maths', type:'shapes',        difficulty:'advanced', question:'A triangle has angles 60° and 80°. What is the third angle?', options:['30°','40°','50°','60°'], answer:'40°' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'7 × 9 = ?', options:['56','61','63','67'], answer:'63' },
  { subject:'maths', type:'wordProblems',  difficulty:'advanced', question:'4 friends share 100 stickers equally. How many each?', options:['20','25','30','35'], answer:'25' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'64 ÷ 8 = ?', options:['6','7','8','9'], answer:'8' },
  { subject:'maths', type:'money',         difficulty:'advanced', question:'An item costs $45. You pay $100. How much change?', options:['$45','$55','$65','$75'], answer:'$55' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'8 × 12 = ?', options:['88','92','96','100'], answer:'96' },
  { subject:'maths', type:'sequences',     difficulty:'advanced', question:'1, 2, 4, 8, 16, ___?', options:['24','28','32','36'], answer:'32' },
  { subject:'maths', type:'wordProblems',  difficulty:'advanced', question:'A class has 32 students. 3/4 are present. How many are present?', options:['20','22','24','26'], answer:'24' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'150 ÷ 10 = ?', options:['10','12','15','20'], answer:'15' },
  { subject:'maths', type:'shapes',        difficulty:'advanced', question:'Area of a square with side 7cm?', options:['42cm²','45cm²','49cm²','52cm²'], answer:'49cm²' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'6 × 9 = ?', options:['48','52','54','58'], answer:'54' },
  { subject:'maths', type:'wordProblems',  difficulty:'advanced', question:'Eggs come in boxes of 12. You need 36 eggs. How many boxes?', options:['2','3','4','5'], answer:'3' },
  { subject:'maths', type:'time',          difficulty:'advanced', question:'2 hours and 45 minutes = how many minutes total?', options:['145','155','160','165'], answer:'165' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'5 × 5 × 4 = ?', options:['80','90','100','110'], answer:'100' },
  { subject:'maths', type:'sequences',     difficulty:'advanced', question:'50, 45, 40, 35, ___?', options:['25','28','30','32'], answer:'30' },
  { subject:'maths', type:'wordProblems',  difficulty:'advanced', question:'7 teams each have 9 players. Total players?', options:['54','60','63','67'], answer:'63' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'200 ÷ 25 = ?', options:['6','7','8','9'], answer:'8' },
  { subject:'maths', type:'logic',         difficulty:'advanced', question:'A number multiplied by itself equals 49. What is the number?', options:['6','7','8','9'], answer:'7' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'13 × 7 = ?', options:['81','87','91','97'], answer:'91' },
  { subject:'maths', type:'wordProblems',  difficulty:'advanced', question:'A tank holds 120 litres and is 3/4 full. How many litres inside?', options:['80','85','90','95'], answer:'90' },
  { subject:'maths', type:'arithmetic',    difficulty:'advanced', question:'7 × 7 = ?', options:['42','47','49','56'], answer:'49' },

  // ─── CHINESE — Beginner (50) — questions entirely in Chinese ──────────────
  { subject:'chinese', type:'characterRecognition', difficulty:'beginner', question:'「日」代表什麼？', options:['太陽','月亮','星星','雲'], answer:'太陽' },
  { subject:'chinese', type:'characterRecognition', difficulty:'beginner', question:'「大」字是什麼意思？', options:['尺寸很大','尺寸很小','不大不小','高山'], answer:'尺寸很大' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'「蘋果」是什麼顏色的？', options:['紅色','藍色','黑色','白色'], answer:'紅色' },
  { subject:'chinese', type:'characterRecognition', difficulty:'beginner', question:'「口」代表什麼身體部位？', options:['嘴巴','眼睛','耳朵','鼻子'], answer:'嘴巴' },
  { subject:'chinese', type:'pinyin',               difficulty:'beginner', question:'「狗」的拼音是？', options:['gǒu','māo','niǎo','yú'], answer:'gǒu' },
  { subject:'chinese', type:'characterRecognition', difficulty:'beginner', question:'「木」代表什麼？', options:['樹木','火','水','石頭'], answer:'樹木' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'「爸爸」是什麼意思？', options:['父親','母親','爺爺','奶奶'], answer:'父親' },
  { subject:'chinese', type:'characterRecognition', difficulty:'beginner', question:'「月」代表什麼？', options:['月亮','太陽','星星','天空'], answer:'月亮' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'「媽媽」是什麼意思？', options:['母親','父親','哥哥','姐姐'], answer:'母親' },
  { subject:'chinese', type:'characterRecognition', difficulty:'beginner', question:'「目」代表什麼身體部位？', options:['眼睛','耳朵','鼻子','嘴巴'], answer:'眼睛' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'「你好」是什麼意思？', options:['打招呼','告別','感謝','道歉'], answer:'打招呼' },
  { subject:'chinese', type:'characterRecognition', difficulty:'beginner', question:'「水」代表什麼意思？', options:['液體，如河流','火焰','泥土','樹木'], answer:'液體，如河流' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'「再見」是什麼意思？', options:['告別','問好','感謝','道歉'], answer:'告別' },
  { subject:'chinese', type:'characterRecognition', difficulty:'beginner', question:'「火」代表什麼意思？', options:['火焰，會發光發熱','液體，如河流','泥土','樹木'], answer:'火焰，會發光發熱' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'一年有多少個月？', options:['十二個月','十個月','十一個月','十三個月'], answer:'十二個月' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'「謝謝」是什麼意思？', options:['感謝','道歉','問好','告別'], answer:'感謝' },
  { subject:'chinese', type:'characterRecognition', difficulty:'beginner', question:'「手」是指哪個身體部位？', options:['手掌和手指','腳和腳趾','頭部','耳朵'], answer:'手掌和手指' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'「小」的反義詞是什麼？', options:['大','多','快','高'], answer:'大' },
  { subject:'chinese', type:'characterRecognition', difficulty:'beginner', question:'「心」代表什麼？', options:['心臟','大腦','手','腳'], answer:'心臟' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'一天有多少小時？', options:['二十四小時','十二小時','三十六小時','四十八小時'], answer:'二十四小時' },
  { subject:'chinese', type:'characterRecognition', difficulty:'beginner', question:'「耳」代表什麼身體部位？', options:['耳朵','眼睛','鼻子','嘴巴'], answer:'耳朵' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'「老師」是做什麼的人？', options:['教學的人','做飯的人','唱歌的人','醫病的人'], answer:'教學的人' },
  { subject:'chinese', type:'characterRecognition', difficulty:'beginner', question:'「天」代表什麼？', options:['天空','地面','山','水'], answer:'天空' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'「好」的反義詞是什麼？', options:['壞','大','快','熱'], answer:'壞' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'「上」的反義詞是什麼？', options:['下','左','右','前'], answer:'下' },
  { subject:'chinese', type:'characterRecognition', difficulty:'beginner', question:'「魚」是什麼樣的動物？', options:['在水中游泳的動物','在天空飛翔的動物','人類的寵物狗','人類的寵物貓'], answer:'在水中游泳的動物' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'「香蕉」是什麼顏色的？', options:['黃色','紅色','綠色','藍色'], answer:'黃色' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'「多」的反義詞是什麼？', options:['少','大','快','好'], answer:'少' },
  { subject:'chinese', type:'characterRecognition', difficulty:'beginner', question:'「白」代表什麼顏色？', options:['白色','黑色','紅色','藍色'], answer:'白色' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'「書」是什麼？', options:['書本','筆','椅子','桌子'], answer:'書本' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'「快」的反義詞是什麼？', options:['慢','小','少','壞'], answer:'慢' },
  { subject:'chinese', type:'characterRecognition', difficulty:'beginner', question:'「鳥」是什麼樣的動物？', options:['在天空飛翔的動物','在水中游泳的動物','人類的寵物狗','人類的寵物貓'], answer:'在天空飛翔的動物' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'什麼時候吃早餐？', options:['早上','中午','晚上','深夜'], answer:'早上' },
  { subject:'chinese', type:'characterRecognition', difficulty:'beginner', question:'「花」代表什麼？', options:['花朵','樹木','草地','石頭'], answer:'花朵' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'「熱」的反義詞是什麼？', options:['冷','慢','少','壞'], answer:'冷' },
  { subject:'chinese', type:'characterRecognition', difficulty:'beginner', question:'「雨」代表什麼天氣現象？', options:['雨水','陽光','雪','風'], answer:'雨水' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'「家」是什麼意思？', options:['住的地方','學習的地方','玩耍的地方','工作的地方'], answer:'住的地方' },
  { subject:'chinese', type:'pinyin',               difficulty:'beginner', question:'「貓」的拼音是？', options:['māo','gǒu','niǎo','yú'], answer:'māo' },
  { subject:'chinese', type:'characterRecognition', difficulty:'beginner', question:'「人」代表什麼？', options:['人類','動物','植物','食物'], answer:'人類' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'「對不起」是什麼意思？', options:['道歉','感謝','告別','問好'], answer:'道歉' },
  { subject:'chinese', type:'pinyin',               difficulty:'beginner', question:'「水」的拼音是？', options:['shuǐ','huǒ','mù','tǔ'], answer:'shuǐ' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'一星期有多少天？', options:['七天','五天','六天','八天'], answer:'七天' },
  { subject:'chinese', type:'characterRecognition', difficulty:'beginner', question:'「山」字有幾個峰頂？', options:['三個','一個','兩個','四個'], answer:'三個' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'「喝」是什麼意思？', options:['飲用','進食','睡覺','奔跑'], answer:'飲用' },
  { subject:'chinese', type:'pinyin',               difficulty:'beginner', question:'「火」的拼音是？', options:['huǒ','shuǐ','mù','tǔ'], answer:'huǒ' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'「小狗」的「小」是什麼意思？', options:['細小的','大大的','快速的','緩慢的'], answer:'細小的' },
  { subject:'chinese', type:'characterRecognition', difficulty:'beginner', question:'哪個字代表「力量」？', options:['力','大','高','強'], answer:'力' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'「車」的意思最接近哪個？', options:['交通工具','食物','動物','植物'], answer:'交通工具' },
  { subject:'chinese', type:'pinyin',               difficulty:'beginner', question:'「人」的拼音是？', options:['rén','mù','shān','yún'], answer:'rén' },
  { subject:'chinese', type:'vocabulary',           difficulty:'beginner', question:'「眼睛」是什麼身體部位？', options:['用來看東西的','用來聽聲音的','用來聞氣味的','用來說話的'], answer:'用來看東西的' },

  // ─── CHINESE — Advanced (50) — questions entirely in Chinese ─────────────
  { subject:'chinese', type:'idioms',    difficulty:'advanced', question:'「一石二鳥」是什麼意思？', options:['一舉兩得','非常困難','速度很快','非常努力'], answer:'一舉兩得' },
  { subject:'chinese', type:'vocabulary', difficulty:'advanced', question:'「勤奮」是什麼意思？', options:['努力工作','懶惰','聰明','勇敢'], answer:'努力工作' },
  { subject:'chinese', type:'idioms',    difficulty:'advanced', question:'「虎頭蛇尾」是什麼意思？', options:['開始積極但結束草率','非常勇敢','一直努力','非常聰明'], answer:'開始積極但結束草率' },
  { subject:'chinese', type:'vocabulary', difficulty:'advanced', question:'「悲傷」的反義詞是什麼？', options:['快樂','憤怒','緊張','驚訝'], answer:'快樂' },
  { subject:'chinese', type:'grammar',   difficulty:'advanced', question:'哪個句子用了正確的「把」字句？', options:['他把書讀了。','他把去學校。','他把很快。','他把是老師。'], answer:'他把書讀了。' },
  { subject:'chinese', type:'idioms',    difficulty:'advanced', question:'「馬到成功」是什麼意思？', options:['立刻成功','非常努力','慢慢進步','困難重重'], answer:'立刻成功' },
  { subject:'chinese', type:'vocabulary', difficulty:'advanced', question:'「驕傲」在哪種情況下有正面意思？', options:['為自己的成就感到自豪','看不起別人','拒絕幫助他人','不聽從勸告'], answer:'為自己的成就感到自豪' },
  { subject:'chinese', type:'fillBlank', difficulty:'advanced', question:'他非常努力學習，___成績非常好。', options:['所以','因為','雖然','但是'], answer:'所以' },
  { subject:'chinese', type:'idioms',    difficulty:'advanced', question:'「半途而廢」是什麼意思？', options:['中途放棄','非常努力','永不放棄','重新開始'], answer:'中途放棄' },
  { subject:'chinese', type:'vocabulary', difficulty:'advanced', question:'「溫柔」是什麼意思？', options:['輕柔體貼','非常強壯','非常勇敢','非常聰明'], answer:'輕柔體貼' },
  { subject:'chinese', type:'grammar',   difficulty:'advanced', question:'選擇正確的量詞：「一___魚」', options:['條','隻','頭','匹'], answer:'條' },
  { subject:'chinese', type:'idioms',    difficulty:'advanced', question:'「畫蛇添足」是什麼意思？', options:['做多餘的事','非常努力','很有創意','速度很快'], answer:'做多餘的事' },
  { subject:'chinese', type:'vocabulary', difficulty:'advanced', question:'「節儉」是什麼意思？', options:['不浪費','非常懶惰','非常貪心','不誠實'], answer:'不浪費' },
  { subject:'chinese', type:'fillBlank', difficulty:'advanced', question:'___他很累，他還是繼續工作。', options:['雖然','因為','所以','如果'], answer:'雖然' },
  { subject:'chinese', type:'idioms',    difficulty:'advanced', question:'「不恥下問」是什麼意思？', options:['不怕向人請教','非常驕傲','從不學習','害怕提問'], answer:'不怕向人請教' },
  { subject:'chinese', type:'vocabulary', difficulty:'advanced', question:'「殘忍」的反義詞是什麼？', options:['仁慈','勇敢','聰明','努力'], answer:'仁慈' },
  { subject:'chinese', type:'grammar',   difficulty:'advanced', question:'「被」字句正確的是？', options:['書被他讀了。','他被讀書了。','讀書了被他。','被書讀了他。'], answer:'書被他讀了。' },
  { subject:'chinese', type:'idioms',    difficulty:'advanced', question:'「對牛彈琴」是什麼意思？', options:['對不懂的人說道理','很有才華','非常努力','喜歡音樂'], answer:'對不懂的人說道理' },
  { subject:'chinese', type:'vocabulary', difficulty:'advanced', question:'「謙虛」是什麼意思？', options:['不自誇','非常驕傲','非常懶惰','非常勇敢'], answer:'不自誇' },
  { subject:'chinese', type:'fillBlank', difficulty:'advanced', question:'如果明天下雨，我們___不去郊遊。', options:['就','所以','因為','雖然'], answer:'就' },
  { subject:'chinese', type:'idioms',    difficulty:'advanced', question:'「一帆風順」是什麼意思？', options:['一切順利','非常困難','速度很快','努力工作'], answer:'一切順利' },
  { subject:'chinese', type:'vocabulary', difficulty:'advanced', question:'「勇氣」是什麼意思？', options:['敢於面對困難的精神','聰明的頭腦','強壯的身體','美麗的外表'], answer:'敢於面對困難的精神' },
  { subject:'chinese', type:'grammar',   difficulty:'advanced', question:'選擇正確的量詞：「一___紙」', options:['張','條','隻','個'], answer:'張' },
  { subject:'chinese', type:'idioms',    difficulty:'advanced', question:'「亡羊補牢」是什麼意思？', options:['事後補救，未為太晚','非常悲傷','勇敢面對','立刻成功'], answer:'事後補救，未為太晚' },
  { subject:'chinese', type:'vocabulary', difficulty:'advanced', question:'「慷慨」是什麼意思？', options:['樂於給予','非常吝嗇','非常懶惰','非常傲慢'], answer:'樂於給予' },
  { subject:'chinese', type:'fillBlank', difficulty:'advanced', question:'他___是我的朋友，___常常幫助我。', options:['不但…而且','雖然…但是','因為…所以','如果…就'], answer:'不但…而且' },
  { subject:'chinese', type:'idioms',    difficulty:'advanced', question:'「守株待兔」是什麼意思？', options:['不勞而獲的想法','非常勤勞','很有智慧','勇於嘗試'], answer:'不勞而獲的想法' },
  { subject:'chinese', type:'vocabulary', difficulty:'advanced', question:'「聰慧」和哪個詞語意思最接近？', options:['智慧','美麗','勇敢','強壯'], answer:'智慧' },
  { subject:'chinese', type:'grammar',   difficulty:'advanced', question:'選擇正確的語句：', options:['他跑得非常快。','他非常跑得快。','他跑非常快得。','他得跑非常快。'], answer:'他跑得非常快。' },
  { subject:'chinese', type:'idioms',    difficulty:'advanced', question:'「功夫不負有心人」是什麼意思？', options:['努力必有收穫','失敗是成功之母','非常困難','速度第一'], answer:'努力必有收穫' },
  { subject:'chinese', type:'vocabulary', difficulty:'advanced', question:'「困惑」是什麼意思？', options:['不明白','非常快樂','非常憤怒','非常悲傷'], answer:'不明白' },
  { subject:'chinese', type:'grammar',   difficulty:'advanced', question:'「她唱歌唱得___美」，空格填什麼？', options:['很','多','過','是'], answer:'很' },
  { subject:'chinese', type:'idioms',    difficulty:'advanced', question:'「三人行，必有我師」是什麼意思？', options:['每個人都有值得學習的地方','三個人一起走路','老師最重要','學習很困難'], answer:'每個人都有值得學習的地方' },
  { subject:'chinese', type:'vocabulary', difficulty:'advanced', question:'「責任」是什麼意思？', options:['應盡的義務','美好的願望','強烈的感情','特別的才能'], answer:'應盡的義務' },
  { subject:'chinese', type:'grammar',   difficulty:'advanced', question:'選擇正確的量詞：「一___牛」', options:['頭','條','隻','張'], answer:'頭' },
  { subject:'chinese', type:'idioms',    difficulty:'advanced', question:'「精益求精」是什麼意思？', options:['不斷追求更好','非常滿足','中途放棄','懶於改進'], answer:'不斷追求更好' },
  { subject:'chinese', type:'vocabulary', difficulty:'advanced', question:'「堅持」是什麼意思？', options:['持之以恆','中途放棄','猶豫不決','逃避困難'], answer:'持之以恆' },
  { subject:'chinese', type:'fillBlank', difficulty:'advanced', question:'我___努力學習，___能考出好成績。', options:['只要…就','雖然…但是','因為…所以','不但…而且'], answer:'只要…就' },
  { subject:'chinese', type:'idioms',    difficulty:'advanced', question:'「青出於藍」是什麼意思？', options:['學生超越老師','老師最偉大','努力學習','永遠謙虛'], answer:'學生超越老師' },
  { subject:'chinese', type:'vocabulary', difficulty:'advanced', question:'「憐憫」是什麼意思？', options:['對他人痛苦的同情','非常憤怒','非常快樂','非常驕傲'], answer:'對他人痛苦的同情' },
  { subject:'chinese', type:'grammar',   difficulty:'advanced', question:'哪個句子正確？', options:['他把作業做完了。','他把做完了作業。','他做完了把作業。','作業把他做完了。'], answer:'他把作業做完了。' },
  { subject:'chinese', type:'idioms',    difficulty:'advanced', question:'「有志者事竟成」是什麼意思？', options:['有決心就能成功','成功需要運氣','天才不需努力','失敗是正常的'], answer:'有決心就能成功' },
  { subject:'chinese', type:'vocabulary', difficulty:'advanced', question:'「勤勞」的反義詞是什麼？', options:['懶惰','聰明','勇敢','謙虛'], answer:'懶惰' },
  { subject:'chinese', type:'fillBlank', difficulty:'advanced', question:'他___努力，成績___進步了。', options:['越來越…越來越','但是…所以','雖然…也','如果…就'], answer:'越來越…越來越' },
  { subject:'chinese', type:'idioms',    difficulty:'advanced', question:'「水滴石穿」是什麼意思？', options:['持之以恆必有成效','力量很大','非常聰明','速度很快'], answer:'持之以恆必有成效' },
  { subject:'chinese', type:'vocabulary', difficulty:'advanced', question:'「慚愧」是什麼意思？', options:['因過錯而難為情','非常快樂','非常憤怒','非常驕傲'], answer:'因過錯而難為情' },
  { subject:'chinese', type:'grammar',   difficulty:'advanced', question:'哪個句子的「雖然」用法正確？', options:['雖然他很累，但他仍繼續工作。','雖然他去學校，所以很開心。','他雖然了，但是很好。','雖然非常努力，因為成功。'], answer:'雖然他很累，但他仍繼續工作。' },
  { subject:'chinese', type:'idioms',    difficulty:'advanced', question:'「知己知彼，百戰百勝」是什麼意思？', options:['了解自己和對手才能獲勝','努力就能成功','失敗是成功之母','速度決定勝負'], answer:'了解自己和對手才能獲勝' },
  { subject:'chinese', type:'vocabulary', difficulty:'advanced', question:'「毅力」是什麼意思？', options:['堅持不懈的意志力','非常聰明的頭腦','強壯的身體','美麗的外表'], answer:'堅持不懈的意志力' },
  { subject:'chinese', type:'idioms',    difficulty:'advanced', question:'「冰凍三尺，非一日之寒」是什麼意思？', options:['積習難改，需長時間形成','天氣非常寒冷','努力就能成功','做事要有計劃'], answer:'積習難改，需長時間形成' },
  { subject:'chinese', type:'vocabulary', difficulty:'advanced', question:'「誠實」的反義詞是什麼？', options:['虛偽','勇敢','聰明','謙虛'], answer:'虛偽' },
]

async function seed() {
  await signInAnonymously(auth)
  const counts = { english: 0, maths: 0, chinese: 0 }
  console.log(`Seeding ${questions.length} questions to Firebase...`)
  for (const q of questions) {
    await addDoc(collection(db, 'questionBank', q.subject, 'questions'), q)
    counts[q.subject]++
    console.log(`  ✓ [${q.subject}/${q.difficulty}] ${q.question.slice(0, 50)}`)
  }
  console.log(`\nDone! English: ${counts.english}, Maths: ${counts.maths}, Chinese: ${counts.chinese}`)
  process.exit(0)
}

seed().catch(err => { console.error(err); process.exit(1) })
